"""Add AI engine model

Revision ID: 5e44ce33d810
Revises: 897e9cc50b3f
Create Date: 2025-12-05 12:15:00.727795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e44ce33d810'
down_revision = '897e9cc50b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_engines',
    sa.Column('provider_name', sa.String(length=100), nullable=False, comment='服务商名称'),
    sa.Column('api_url', sa.String(length=500), nullable=False, comment='API地址'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API密钥'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('api_params', sa.Text(), nullable=True, comment='额外API参数(JSON格式)'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标CSS类名'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_site_rules_site_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_site_rules_site_name'), ['site_name'], unique=1)

    op.drop_table('ai_engines')
    # ### end Alembic commands ###
